# -*- coding: utf-8 -*-
"""CodeAlpha_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o507mYEa4QbDIsU9xvfHiz4yecFSwxI3
"""

import random
random_number = random.randint(0, 4)

words = ['blue', 'red', 'green', 'yellow', 'gray']
target_word = words[random_number]
check_word = target_word
predicted_word = '-' * len(target_word)
incorrect = 0
correct = []
while True :
  if predicted_word == check_word :
    print("you won")
    break
  if incorrect == 6 :
    print("you lost")
    break
  user_input = input("enter a char")
  if len(user_input) > 1 :
    print("enter only one char")
    continue
  if user_input in target_word :
    correct.append(user_input)
    index_char = target_word.index(user_input)
    predicted_word = predicted_word[:index_char] + user_input + predicted_word[index_char + 1:]
    target_word = target_word[:index_char] + "-" + target_word[index_char + 1:]
    print(predicted_word)
  else :
    incorrect += 1
    print("incorrect guesses ", incorrect, " : 6")

